### ISSUE TITLE
`stroke-width` / strokeWidth not being applied to the shape elements

### ISSUE THREAD

**Issue by cworsley4** [impulse/heroicons-react#7]
The stoke width, among others, is not being applied to the `<path>` element for ChatAlt2. I have also seen instances where stroke-width={2} is hard coded. This should be something that is set from the strokeWidth prop, yes?

**Comment by coderinblack08** [comment]
Something else I want to bring up here, is it possible to get outlined icons, and are there plans to integrate them into this library?

**Comment by ecklf** [comment]
@cworsley4 good point (did notice that too). The problem is that many values are - accidentally - hardcoded so it's a bit difficult to maintain. I will look into a solution soon.

@coderinblack08 outlined icons are already available https://github.com/impulse/heroicons-react/tree/master/src/icons. They are suffixed with `Outline`
